# Keycloak с предварительной сборкой
FROM quay.io/keycloak/keycloak:24.0.2 as builder

# Установка провайдеров
RUN /opt/keycloak/bin/kc.sh build

# Финальный образ
FROM quay.io/keycloak/keycloak:24.0.2
COPY --from=builder /opt/keycloak/ /opt/keycloak/

# Копирование конфигурации realm
COPY keycloak-config/hotel-realm.json /opt/keycloak/data/import/

# Параметры запуска
ENTRYPOINT ["/opt/keycloak/bin/kc.sh"]
CMD ["start-dev", "--import-realm"]