version: '3.8'

services:
  mariadb:
    image: mariadb:11.3
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hoteldb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    ports:
      - "3306:3306"


  wildfly:
    build:
      context: .
      dockerfile: wildfly/Dockerfile
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
      - "9990:9990"
    restart: unless-stopped

volumes:
  mariadb_data:
