version: '3.8'

services:
  # База данных MariaDB
  mariadb:
    image: mariadb:11.3
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hoteldb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    ports:
      - "3306:3306"
    volumes:
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - hotel-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "dbuser", "-pdbpass"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Keycloak для аутентификации
  keycloak:
    build:
      context: src/main/java
      dockerfile: src/main/java/Dockerfile.keycloak
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: mariadb
      KC_DB_URL: jdbc:mariadb://mariadb:3306/keycloak
      KC_DB_USERNAME: dbuser
      KC_DB_PASSWORD: dbpass
      KC_HEALTH_ENABLED: true
    ports:
      - "8081:8080"
    volumes:
      - ./keycloak-config:/opt/keycloak/data/import
    networks:
      - hotel-network
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  # Сервер приложений WildFly
  wildfly:
    build:
      context: src/main/java
      dockerfile: src/main/java/Dockerfile.wildfly
    container_name: wildfly
    ports:
      - "8080:8080"
      - "9990:9990"
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: hoteldb
      DB_USER: dbuser
      DB_PASSWORD: dbpass
      KEYCLOAK_URL: http://keycloak:8080
    volumes:
      - ./wildfly-config:/wildfly-config
    networks:
      - hotel-network
    depends_on:
      mariadb:
        condition: service_healthy
      keycloak:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/hotel-api/api/health"]
      interval: 30s
      timeout: 5s
      retries: 5

networks:
  hotel-network:
    driver: bridge